version: "3.8"
services:
  
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      
  rabbitmq:
    container_name: rabbitmq
    build: 
      context: .
      dockerfile: ./Rabbitmq.Dockerfile
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  order-service:
    container_name: order-service
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
    ports:
    - "4000:4000"
    environment:
      - PORT=4000
      - DOCKER=true
    depends_on: 
      - mongodb
      - rabbitmq
    links:
      - rabbitmq
    restart: on-failure

  transporter-service:
    container_name: transporter-service
    build:
       context: .
       dockerfile: ./transporter-service/Dockerfile
    ports:
    - "5000:5000"
    environment:
      - PORT=5000
      - DOCKER=true
    depends_on:
      - mongodb
      - rabbitmq
    links:
      - rabbitmq
    restart: on-failure
    
  catalog-command-service:
    container_name: catalog-command-service
    build:
      context: .
      dockerfile: ./catalog-command-service/Dockerfile
    ports:
    - "6000:6000"
    environment:
      - PORT=6000
      - DOCKER=true
    depends_on: 
    - mongodb
    - rabbitmq
    links: 
      - rabbitmq
    restart: on-failure

  support-service:
    container_name: support-service
    build:
      context: .
      dockerfile: ./support-service/Dockerfile
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - DOCKER=true
    depends_on: 
      - mongodb
    links:
      - rabbitmq
    restart: on-failure

  catalog-query-service:
    container_name: catalog-query-service
    build:
      context: .
      dockerfile: ./catalog-query-service/Dockerfile
    ports:
    - "8000:8000"
    environment:
      - PORT=8000
      - DOCKER=true
    depends_on: 
      - rabbitmq
    links: 
      - rabbitmq
    restart: on-failure

volumes:
  mongodata: