version: "3.8"
services:
  
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - mongodata:/data/db

  order-service:
    container_name: order-service
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
    ports:
    - "4000:4000"
    depends_on: 
    - mongodb
    environment:
      - PORT=4000
      - DOCKER=true
   # - rabbitmq

  # transporter-service:
  #   container_name: transporter-service
  #   build:
  #     context: .
  #     dockerfile: ./transporter-service/Dockerfile
  #   ports:
  #   - "5000:5000"
  #   depends_on: 
  #   - mongodb
  #   environment:
  #     - PORT=5000
  #     - DOCKER=true
    # - rabbitmq
    
  catalog-service:
    container_name: catalog-service
    build:
      context: .
      dockerfile: ./catalog-service/Dockerfile
    ports:
    - "6000:6000"
    depends_on: 
    - mongodb
    environment:
      - PORT=6000
      - DOCKER=true
    # - rabbitmq

  support-service:
    container_name: support-service
    build:
      context: .
      dockerfile: ./support-service/Dockerfile
    ports:
      - "7000:7000"
    depends_on: 
      - mongodb
    environment:
      - PORT=7000
      - DOCKER=true
    # - rabbitmq


  # rabbitmq:
  #   image: rabbitmq
  #   ports:
  #   - "5672:5672"
volumes:
  mongodata: